name: docker-hub-description

on:
  push:
    branches: [ "master" ]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Update docker hub description
        uses: peter-evans/dockerhub-description@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          repository: visibilityspots/route53-dyndns
          short-description: ${{ github.event.repository.description }}
